server:
  port: 9000
  
spring:
  cloud:
    gateway:
      routes:
      - id:customerService
        uri:http://localhost:8081/
        
      - id:bookingService
        uri:http://localhost:8082/